org: jpbogle
app: cardinal
service: cardinal-namespaces
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  http:
    cors: true

package:
  individually: true
  exclude:
    - "./node_modules"
    - "./yarn.lock"

functions:
  twitter-approver:
    handler: twitter-approver/handler.approve
    timeout: 30
    environment:
      TWITTER_SOLANA_KEY: ${ssm:/TWITTER_SOLANA_KEY~true}
    events:
      - http:
          path: /twitter/approve
          method: get
  twitter-revoker:
    handler: twitter-revoker/handler.revoke
    timeout: 30
    environment:
      TWITTER_SOLANA_KEY: ${ssm:/TWITTER_SOLANA_KEY~true}
    events:
      - http:
          path: /twitter/revoke
          method: get
  twitter-proxy:
    handler: twitter-proxy/handler.proxy
    events:
      - http:
          path: /twitter/proxy
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-include-dependencies
